# ExperimentSettings
project_name: 'CXRTAG'
experiment_name: 'Chexfusion'
description: 'Chexfusion'
seed: 9233
# SaveSettings
save_dir: '/hy-tmp/Results/'

# DataInputSettings
image_dir: '/hy-tmp/files256/'
image_size: 224
clip_features_path: '/hy-tmp/clip.npz'
class_name:   
  [ Enlarged Cardiomediastinum,
    Cardiomegaly,
    Lung Opacity,
    Lung Lesion,
    Edema,
    Consolidation,
    Atelectasis,
    Pneumothorax,
    Pleural Effusion,
    Pleural Other,
    Fracture,
    Support Devices,
    No Finding ]
class_instance_nums:
  [ 30119,
    76900,
    79931,
    2533,
    38574,
    16038,
    67597,
    14983,
    69240,
    675,
    11883,
    89140,
    41869, ]
total_instance_num: 264849

# DataLoaderSettings
dataset_name: 'mimic_cxr'
num_workers: 4
batch_size: 32

# ModelSettingss
vision_model: 'resnet101'
vision_channels: 2048
load_pretrained: False


# TrainerSettings
n_gpu: 1
epochs: 20
early_stop: 5
monitor_metric: 'mAP'

# Optimization
loss: 'asl'
# init_lr: !!float 3e-5
# min_lr: !!float 5e-6
# warmup_lr: !!float 5e-7
# weight_decay: 0.05
# warmup_steps: 3000
lr: !!float 3e-5
warmup_steps: 300
